name: CMake

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install sys packages
      run: sudo apt update && sudo apt install -y gcc-11 python3-pip && pip3 install conan

    - name: Setup Conan
      run: | 
        mkdir -p /home/runner/.conan/profiles && 
        cat << EOF > /home/runner/.conan/profiles/default
        [settings]
        os=Linux 
        os_build=Linux
        arch=x86_64
        arch_build=x86_64
        compiler=gcc
        compiler.version=11
        compiler.libcxx=libstdc++11
        build_type=Release
        [options]
        [build_requires]
        [env]
        EOF

    - name: Pull dependencies
      run: |
        conan create ${{github.workspace}}/conan/tensorflow && 
        conan create ${{github.workspace}}/conan/cppflow &&
        conan create ${{github.workspace}}/conan/csv-parser &&
        conan install ${{github.workspace}}/cpp/core --build=missing

    - name: Configure CMake
      run: cmake ./cpp -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DBUILD_TEST=1

    - name: Build
      run: VERBOSE=1 cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j6

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ln -s ../neural-net neural-net && ctest -C ${{env.BUILD_TYPE}} --output-on-failure
      
